spring:
  application:
    name: pure-dubbo-consumer
  dubbo:
    application:
      id: ${spring.application.name}
      name: ${spring.application.name}
    registry:
      address: zookeeper://127.0.0.1:2181;zookeeper://127.0.0.1:2182;zookeeper://127.0.0.1:2183
      group: kute
#      username:
#      password:
    protocol:
      name: dubbo
      port: 20880
  profiles:
    active: default
server:
  port: 8080



